name: mitra
description: An AI Assistant (ChatBot, Image Generator & Language Translator) App Based on ChatGPT developed by Manish Kumar

publish_to: 'none' 

# App Version
version: 1.0.2+2

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Core
  firebase_core: ^3.8.0

  # Cloud Firestore
  cloud_firestore: ^5.5.0

  # Firebase Authentication
  firebase_auth: ^5.3.3


  # iOS Styled Icons
  cupertino_icons: ^1.0.8

  # For using Lottie Animations
  lottie: ^3.1.2

  # For Hive Database
  # hive: ^4.0.0-dev.2
  # isar_flutter_libs: ^4.0.0-dev.13

  # Using this version due to less apk size
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # For Accessing Storage Path
  path_provider: ^2.1.3

  # For State Management
  get: ^4.6.6

  # For Custom Animation
  flutter_animate: ^4.5.0
  animated_text_kit: ^4.2.2

  # For API Call
  http: ^1.2.2

  # For AI Image Generation
  dart_openai: ^5.1.0
  cached_network_image: ^3.3.1
  
  # Google Gemini Ai Integration
  google_generative_ai: ^0.4.3

  # For Google Language Translate
  translator_plus: ^1.0.1

  # For Saving Image to Gallery
  gallery_saver_updated: ^3.0.0

  # For Sharing Image
  share_plus: ^10.1.2

  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Encourages Good Practices
  flutter_lints: ^4.0.0

  # For Changing App Icon
  # icons_launcher: ^2.1.7

flutter:

  # Enables Material Design
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/
    - assets/.env
