// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8WOMt4FRFKcuVdLlwYX0LApZWOWvn7iI',
    appId: '1:107889493450:web:b5c4bb9907799b29cfbb33',
    messagingSenderId: '107889493450',
    projectId: 'mitra-chatbots',
    authDomain: 'mitra-chatbots.firebaseapp.com',
    storageBucket: 'mitra-chatbots.firebasestorage.app',
    measurementId: 'G-2MTB61FNN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBetKQeOkA-52p04bkcfTti9kWl0HYWoqg',
    appId: '1:107889493450:android:e81cb094dd55e311cfbb33',
    messagingSenderId: '107889493450',
    projectId: 'mitra-chatbots',
    storageBucket: 'mitra-chatbots.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1jFQDOaekFU0nlNCi1voKl8-ypAZju90',
    appId: '1:107889493450:ios:c312997f212c8683cfbb33',
    messagingSenderId: '107889493450',
    projectId: 'mitra-chatbots',
    storageBucket: 'mitra-chatbots.firebasestorage.app',
    androidClientId: '107889493450-ki8v6rokn4uusmgkmaku7jbdjudp477g.apps.googleusercontent.com',
    iosClientId: '107889493450-c3kk6iskkch2epf8n8t8vh582ore0aml.apps.googleusercontent.com',
    iosBundleId: 'com.example.mitra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1jFQDOaekFU0nlNCi1voKl8-ypAZju90',
    appId: '1:107889493450:ios:c312997f212c8683cfbb33',
    messagingSenderId: '107889493450',
    projectId: 'mitra-chatbots',
    storageBucket: 'mitra-chatbots.firebasestorage.app',
    androidClientId: '107889493450-ki8v6rokn4uusmgkmaku7jbdjudp477g.apps.googleusercontent.com',
    iosClientId: '107889493450-c3kk6iskkch2epf8n8t8vh582ore0aml.apps.googleusercontent.com',
    iosBundleId: 'com.example.mitra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8WOMt4FRFKcuVdLlwYX0LApZWOWvn7iI',
    appId: '1:107889493450:web:8d51a0de4136656acfbb33',
    messagingSenderId: '107889493450',
    projectId: 'mitra-chatbots',
    authDomain: 'mitra-chatbots.firebaseapp.com',
    storageBucket: 'mitra-chatbots.firebasestorage.app',
    measurementId: 'G-H6D6BW66HN',
  );
}
